### ISSUE TITLE
This line causes issues when trying to install arrayop via renv

### ISSUE THREAD

**Issue by dvg-p4** [Paradigm4/ArrayOpR#32]
https://github.com/Paradigm4/ArrayOpR/blob/ee14773572cfbc463bd05e5b47161b3631af0e2e/DESCRIPTION#L28

It seems to be trying to pull master, rather than the latest release--see:
https://github.com/rstudio/renv/issues/736
https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html
https://remotes.r-lib.org/articles/dependencies.html

I think adding `@*release` to the end of this line would probably make it work right?

**Comment by smoore-p4** [comment]
The idea wasn't to pin it to a specific `scidb` package, but that it had to be version 3.1.2 or later. So... latest is fine?

**Comment by dvg-p4** [comment]
Yup, looks like most of the trouble I was having is an R3 exclusive bug in renv, not really our fault.
