### ISSUE TITLE
match on large number of operands

### ISSUE THREAD

**Issue by ksens** [Paradigm4/ArrayOpR#4]
@wenweiP4 

When I run `match` on a few operands:

```R
repo$query(RG_PUBLIC$PROJECT$match(data.frame(project_id = c(1:4, 7:9)), op_mode = 'filter'))
```

the appropriate AFL is generated:

```
filter(rg_public.PROJECT,project_id=1 or project_id=2 or project_id=3 or project_id=4 or project_id=7 or project_id=8 or project_id=9)
```

However, when the number of operands is greater than 400, 

```R
repo$query(RG_PUBLIC$PROJECT$match(data.frame(project_id = c(1:401)), op_mode = 'filter'))
```

I get the error:
```
Error id: scidb::SCIDB_SE_PARSER::SCIDB_LE_EXPRESSION_HAS_TOO_MANY_OPERANDS
Error description: Error during query parsing. A SciDB expression may have no more than 400 operands.
```

What is the preferred way to run a match in these cases. My data for matching exists in a data.frame -- maybe I have to upload the array first and then do a join?

**Comment by ksens** [comment]
FYI -- I used `master` branch of arrayop.

**Comment by wenweiP4** [comment]
@ksens If `project_id` is a dimension, then
```{r}
uploaded = repo$upload_df(df, RG_PUBLIC$PROJECT)
result = RG_PUBLIC$PROJECT$match(uploaded, op_mode = 'cross_between')
```

If `project_id` is an attribute, 
```{r}
uploaded = repo$upload_df(df, RG_PUBLIC$PROJECT)
result = RG_PUBLIC$PROJECT$join(uploaded, on_both = 'project_id')
# If there are other dimensions on PROJECT you want to keep, then
result = RG_PUBLIC$PROJECT$join(uploaded, on_both = 'project_id', setting = list(keep_dimensions = 1))
```

The reason why there is no `join` mode in `arrayOp$match` function is that both `filter` and `cross_between` return arrays without schema changes, but `equi_join` does change the schema.
