### ISSUE TITLE
Specifying `Remotes: Paradigm4/SciDBR` can cause issues with RSPM-based deployments

### ISSUE THREAD

**Issue by dvg-p4** [Paradigm4/ArrayOpR#40]
Since the source for SciDBR will be RSPM, not github, for those deployments. 

https://github.com/Paradigm4/ArrayOpR/blob/f3e210b0293227edaba5f65c91d1095b21d7c82e/DESCRIPTION#L29

Related to #32

**Comment by jwimberl** [comment]
Resolved by #41
