### ISSUE TITLE
Running into AFL error when running vignette

### ISSUE THREAD

**Issue by ksens** [Paradigm4/ArrayOpR#7]
When running the following line from ArrayOp vignette

https://github.com/Paradigm4/ArrayOpR/blob/9350b934ff109427e195cad1653f793fa6c0f53e/vignettes/arrayop.Rmd#L151

I got:

```
Error: HTTP error 406 UserException in file: src/query/Expression.cpp function: evaluate line: 1263 instance: s0-i30 (30) Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_ERROR_IN_UDF Error description: Query processor error. Error 'Invalid special open parenthesis.' in user-defined function 'regex'. Failed query id: 0.1636627923900222928
```

@smoore-p4 Can you check if you also face this error?

## Versions

```R
packageVersion('scidb')
# [1] ‘3.0.4’
packageVersion('arrayop')
# [1] ‘1.4.1’
```

```sh
scidb --version
# SciDB Version: 21.8.1
# Build Type: RelWithDebInfo
# Commit: e2c495f3
```

**Comment by smoore-p4** [comment]
I just tried it on SciDB 19.11, and it seems to work. It seems to be something about the regex processor in SciDB.
if you try running that line with `to_afl()` instead of `to_df()` you should get something like:

> arr_existing$filter(Plant %contains% "3", Plant %starts_with% "Q", Treatment %contains% "chill", Treatment %like% "chill[a-z]{2}$")$to_afl()
> [1] "filter(test_CO2,regex(Plant, '(?i).*3.*') and regex(Plant, '(?i)Q.*') and regex(Treatment, '(?i).*chill.*') and regex(Treatment, '(?i)chill[a-z]{2}$'))"

I'm wondering if regex processing changed in 21.8 ?

**Comment by smoore-p4** [comment]
Try running either of the following and see if it works:

```
arr_existing$filter(Plant %contains% "3", Plant %starts_with% "Q", Treatment %contains% "chill", Treatment %like% "chill[a-z]{2}$", .regex_function="rsub").to_df()

arr_existing$filter(Plant %contains% "3", Plant %starts_with% "Q", Treatment %contains% "chill", Treatment %like% "chill[a-z]{2}$", .ignore_case=F).to_df()
```

**Comment by ksens** [comment]
@smoore-p4 

The first one errors out:

```R
arr_existing$filter(Plant %contains% "3", Plant %starts_with% "Q", Treatment %contains% "chill", Treatment %like% "chill[a-z]{2}$", .regex_function="rsub")$to_df()
```

yields

```
Error in assert(!rlang::has_length(obj), ...) : Please use == for equality tests with args: .regex_function
```

The second one works:

```R
arr_existing$filter(Plant %contains% "3", Plant %starts_with% "Q", Treatment %contains% "chill", Treatment %like% "chill[a-z]{2}$", .ignore_case=F)$to_df()
# works
```

As @mpietras-p4 mentioned over group Slack, the error reported by me might have to do with the fact that some regex behaviour changed between 19.11 and 20.10+. 

@mpietras-p4 -- do you have a Jira ticket referencing the behaviour change noticed by you? If you reported the issue via email, can you ask Dev and check if they have a Jira ticket for the issue?

**Comment by mpietras-p4** [comment]
@ksens I did open a Jira ticket with dev here: https://paradigm4.atlassian.net/browse/SDB-7457

**Comment by ksens** [comment]
Thanks @mpietras-p4 ! Looks like the Jira ticket was not assigned to anyone in Dev yet. Copied @JAKinchen on the Jira ticket so that he can assign the ticket to someone.

@smoore-p4 -- feel free to close this ticket, as the issue is a scidb issue, and is not an arrayop issue.

**Comment by smoore-p4** [comment]
Ah, looks like I messed up the first one, @ksens 
Can you try this one and make sure it doesn't error out?
```
arr_existing$filter(Plant %contains% "3", Plant %starts_with% "Q", Treatment %contains% "chill", Treatment %like% "chill[a-z]{2}$", .regex_func = "rsub")$to_df()
```

(I had `.regex_function =` when it should have been `.regex_func =` )
I just want to make sure that one works before closing.

**Comment by ksens** [comment]
Yup, works.

**Comment by smoore-p4** [comment]
Closing since it looks like a SciDB issue.
